# Generated by Django 5.0.14 on 2026-09-29 01:59

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('customer_type', models.CharField(choices=[('WALK_IN', 'Walk-in retail'), ('GARAGE', 'Garage'), ('FLEET', 'Fleet'), ('INDIVIDUAL', 'Individual')], default='WALK_IN', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan telephone number.', regex='^(?:\\+254|0)[17]\\d{8}$')])),
                ('kra_pin', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan KRA PIN.', regex='^[A-Za-z][0-9]{9}[A-Za-z]$')])),
                ('credit_limit_minor', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_balance_minor', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_days', models.PositiveIntegerField(default=30)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('loyalty_tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=20)),
                ('lifetime_points_earned', models.IntegerField(default=0)),
                ('lifetime_points_redeemed', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan telephone number.', regex='^(?:\\+254|0)[17]\\d{8}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entry_type', models.CharField(choices=[('CREDIT_SALE', 'Credit sale'), ('PAYMENT_RECEIVED', 'Payment received'), ('CREDIT_NOTE', 'Credit note'), ('DEBIT_ADJUSTMENT', 'Debit adjustment')], max_length=40)),
                ('amount_delta_minor', models.BigIntegerField()),
                ('balance_before_minor', models.BigIntegerField()),
                ('balance_after_minor', models.BigIntegerField()),
                ('reference_type', models.CharField(max_length=40)),
                ('reference_id', models.UUIDField(db_index=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customers.customer')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='customers.customer')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customergroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('registration_plate', models.CharField(db_index=True, max_length=20)),
                ('chassis_vin', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_vehicles', to='vehicles.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('REDEEMED', 'Redeemed'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('points', models.IntegerField()),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'phone'], name='customers_c_tenant__6d2a04_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'kra_pin'], name='customers_c_tenant__1494be_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('credit_limit_minor__gte', 0)), name='chk_customer_credit_limit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('current_balance_minor__gte', 0)), name='chk_customer_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer', 'name', 'phone'), name='uniq_customer_contact'),
        ),
        migrations.AddConstraint(
            model_name='customergroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_customer_group_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['tenant', 'customer', '-created_at'], name='customers_c_tenant__065800_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('balance_after_minor', django.db.models.expressions.CombinedExpression(models.F('balance_before_minor'), '+', models.F('amount_delta_minor')))), name='chk_customer_ledger_integrity'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('balance_after_minor__gte', 0)), name='chk_customer_ledger_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customervehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'registration_plate'), name='uniq_active_customer_vehicle_plate_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.CheckConstraint(check=models.Q(('balance_after', django.db.models.expressions.CombinedExpression(models.F('balance_before'), '+', models.F('points')))), name='chk_loyalty_ledger_integrity'),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.CheckConstraint(check=models.Q(('balance_after__gte', 0)), name='chk_loyalty_balance_nonnegative'),
        ),
    ]
