# Generated by Django 5.0.14 on 2026-09-29 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('visibility_mode', models.CharField(choices=[('PUBLIC', 'Public catalog'), ('NEGOTIATED', 'Negotiated pricing')], default='PUBLIC', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_connections', to='tenancy.tenant')),
                ('supplier_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_connections', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='supplierconnection',
            constraint=models.UniqueConstraint(fields=('retailer_tenant', 'supplier_tenant'), name='uniq_cross_tenant_supplier_pair'),
        ),
        migrations.AddConstraint(
            model_name='supplierconnection',
            constraint=models.CheckConstraint(check=models.Q(('retailer_tenant', models.F('supplier_tenant')), _negated=True), name='chk_connection_tenants_distinct'),
        ),
    ]
