# Generated by Django 5.0.14 on 2026-09-29 07:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_network', '0001_initial'),
        ('tenancy', '0002_tenantdomain_tenantfeature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('scope', models.CharField(max_length=100)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('granting_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_granted', to='tenancy.tenant')),
                ('receiving_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_received', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.UniqueConstraint(fields=('granting_tenant', 'receiving_tenant', 'scope'), name='uniq_tenant_consent_scope'),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.CheckConstraint(check=models.Q(('granting_tenant', models.F('receiving_tenant')), _negated=True), name='chk_consent_tenants_distinct'),
        ),
    ]
