# Generated by Django 5.0.14 on 2026-09-29 02:01

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branchuser_branchuser_uniq_branch_user_membership'),
        ('catalog', '0002_barcode_productimage_productvariant_and_more'),
        ('customers', '0001_initial'),
        ('offline_sync', '0001_initial'),
        ('pos', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payment_number', models.CharField(db_index=True, max_length=60)),
                ('amount_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('document_number', models.CharField(db_index=True, max_length=60)),
                ('receipt_number', models.CharField(db_index=True, max_length=60)),
                ('cashier_name_snapshot', models.CharField(max_length=150)),
                ('customer_name_snapshot', models.CharField(max_length=200)),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=30)),
                ('customer_pin_snapshot', models.CharField(blank=True, max_length=11)),
                ('currency_code', models.CharField(default='KES', max_length=3)),
                ('subtotal_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('change_minor', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('VOIDED', 'Voided'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('etims_status', models.CharField(default='QUEUED_OFFLINE', max_length=30)),
                ('etims_cu_number', models.CharField(blank=True, max_length=60)),
                ('etims_signature', models.CharField(blank=True, max_length=200)),
                ('etims_qr_url', models.URLField(blank=True, max_length=500)),
                ('etims_transmitted_at', models.DateTimeField(blank=True, null=True)),
                ('loyalty_points_earned', models.IntegerField(default=0)),
                ('loyalty_points_redeemed', models.IntegerField(default=0)),
                ('loyalty_discount_minor', models.BigIntegerField(default=0)),
                ('loyalty_tier', models.CharField(blank=True, max_length=20)),
                ('is_offline_created', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='branches.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='tenancy.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
                ('offline_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offline_sync.syncdevice')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.register')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pos.cashsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('allocated_amount_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.payment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('amount_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(max_length=255)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='sales.sale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('part_sku', models.CharField(max_length=60)),
                ('part_name', models.CharField(max_length=255)),
                ('oem_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_minor', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate_code', models.CharField(choices=[('A', 'Standard VAT'), ('B', 'Zero rated'), ('C', 'Petroleum VAT'), ('E', 'Exempt')], default='A', max_length=10)),
                ('line_total_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('amount_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('canonical_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sale_payments', to='sales.payment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='sales.paymentmethod')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('tenant', 'payment_number'), name='uniq_payment_number_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'branch', '-created_at'], name='sales_sale_tenant__05361d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'customer', '-created_at'], name='sales_sale_tenant__67c103_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'etims_status'], name='sales_sale_tenant__cc3963_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('tenant', 'document_number'), name='uniq_sale_docnum_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('tenant', 'receipt_number'), name='uniq_sale_receipt_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('total_minor__gte', 0)), name='chk_sale_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('subtotal_minor', django.db.models.expressions.CombinedExpression(models.F('total_minor'), '-', models.F('tax_minor')))), name='chk_sale_subtotal_consistent'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='chk_sale_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(check=models.Q(('line_total_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price_minor')), '-', models.F('discount_minor')))), name='chk_saleitem_line_total_consistent'),
        ),
    ]
