# Generated by Django 4.2.20 on 2026-09-28 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('CASHIER', 'Certified Cashier & POS Operator'), ('STOREKEEPER', 'Storekeeper & Inventory Clerk'), ('PARTS_SALES', 'Counter Parts Sales Rep'), ('BRANCH_MANAGER', 'Branch Operations Manager'), ('ACCOUNTANT', 'Auditor & Head Accountant'), ('TENANT_ADMIN', 'Tenant Administrator')], default='CASHIER', max_length=50)),
            ],
        ),
    ]
