upstream my_motii_core { server core:8000; }

server {
    listen 80;
    server_name admin.my_motii.local;

    location /django-admin/ { proxy_pass http://my_motii_core; include /etc/nginx/proxy_common.conf; }
    location /internal/     { proxy_pass http://my_motii_core; include /etc/nginx/proxy_common.conf; }
    location /static/       { alias /var/www/static/; }
    location /media/        { alias /var/www/media/;  }
}