upstream my_motii_api { server api:8001; }

server {
    listen 80;
    server_name api.my_motii.local;

    location /api/      { proxy_pass http://my_motii_api; include /etc/nginx/proxy_common.conf; }
    location /ws/       { proxy_pass http://my_motii_api; include /etc/nginx/proxy_ws.conf;     }
    location /webhooks/ { proxy_pass http://my_motii_api; include /etc/nginx/proxy_common.conf; }
    location /healthz   { proxy_pass http://my_motii_api; }
}