# Generated by Django 5.0.14 on 2026-09-29 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_barcode_productimage_productvariant_and_more'),
        ('tenancy', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalentPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('part_number', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('OEM', 'Original equipment manufacturer'), ('OES', 'Original equipment supplier'), ('PREMIUM_AFTERMARKET', 'Premium aftermarket'), ('STANDARD_AFTERMARKET', 'Standard aftermarket')], default='PREMIUM_AFTERMARKET', max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalents', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OemPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('part_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oem_parts', to='catalog.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OemSupersession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='fitment.oempart')),
                ('old_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='fitment.oempart')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartFitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oem_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='fitment.oempart')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='vehicles.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part_fitment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_links', to='fitment.partfitment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitment_links', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='equivalentpart',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'brand', 'part_number'), name='uniq_equivalent_part_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='oemsupersession',
            constraint=models.UniqueConstraint(fields=('old_part', 'new_part'), name='uniq_oem_supersession_pair'),
        ),
        migrations.AddConstraint(
            model_name='oemsupersession',
            constraint=models.CheckConstraint(check=models.Q(('old_part', models.F('new_part')), _negated=True), name='chk_oem_supersession_distinct'),
        ),
        migrations.AddIndex(
            model_name='partfitment',
            index=models.Index(fields=['oem_part', 'vehicle_model'], name='fitment_par_oem_par_a84d7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='partfitment',
            constraint=models.UniqueConstraint(fields=('oem_part', 'vehicle_model', 'position'), name='uniq_canonical_fitment'),
        ),
        migrations.AddIndex(
            model_name='productfitment',
            index=models.Index(fields=['tenant', 'product'], name='fitment_pro_tenant__c02fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='productfitment',
            index=models.Index(fields=['tenant', 'part_fitment'], name='fitment_pro_tenant__ed36ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='productfitment',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'part_fitment'), name='uniq_tenant_product_fitment'),
        ),
    ]
