# Generated by Django 5.0.14 on 2026-09-29 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_barcode_productimage_productvariant_and_more'),
        ('fitment', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOemNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oem_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='fitment.oempart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oem_numbers', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'product'], name='fitment_pro_tenant__bdfbe7_idx'), models.Index(fields=['tenant', 'oem_part'], name='fitment_pro_tenant__c39339_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productoemnumber',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'oem_part'), name='uniq_product_oem_mapping'),
        ),
        migrations.AddConstraint(
            model_name='productoemnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant', 'product'), name='uniq_primary_oem_per_product'),
        ),
    ]
