# Generated by Django 4.2.20 on 2026-09-28 22:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_code', models.CharField(default='+254', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(default='KSh', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('tenant_type', models.CharField(choices=[('RETAILER', 'Auto Spare Retailer & Counter POS'), ('SUPPLIER', 'Wholesale Importer & Parts Distributor'), ('HYBRID', 'Hybrid Retailer & Wholesale Distributor'), ('GARAGE', 'Independent Garage & Workshop'), ('PLATFORM', 'Platform Operator & Super Administrator')], db_index=True, default='RETAILER', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('trading_as', models.CharField(blank=True, max_length=200)),
                ('kra_pin', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan KRA PIN.', regex='^[A-Za-z][0-9]{9}[A-Za-z]$')])),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan telephone number.', regex='^(?:\\+254|0)[17]\\d{8}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5)),
                ('whvat_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('enable_loyalty', models.BooleanField(default=True)),
                ('enable_offline_sync', models.BooleanField(default=True)),
                ('enforce_strict_stock', models.BooleanField(default=True)),
                ('allow_credit_sales', models.BooleanField(default=True)),
                ('default_credit_days', models.PositiveIntegerField(default=30)),
                ('receipt_header_text', models.TextField(blank=True, default='Dealers in Genuine Japanese Auto Spares & Accessories')),
                ('receipt_footer_policy', models.TextField(default='Goods once sold can only be exchanged within 7 days in original packaging. No cash refunds.')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.currency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='country',
            name='default_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_for_countries', to='tenancy.currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
