# Generated by Django 5.0.14 on 2026-09-29 07:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtimsDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('cu_number', models.CharField(db_index=True, max_length=60)),
                ('scdc_number', models.CharField(max_length=60)),
                ('fiscal_signature', models.CharField(max_length=200)),
                ('qr_code_url', models.URLField(max_length=500)),
                ('transmission_status', models.CharField(default='SUBMITTED_SUCCESS', max_length=30)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtimsError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('error_code', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtimsResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cu_number', models.CharField(blank=True, max_length=60)),
                ('scdc_number', models.CharField(blank=True, max_length=60)),
                ('qr_code_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtimsSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payload_sent', models.JSONField()),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtimsConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('tin', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan KRA PIN.', regex='^[A-Za-z][0-9]{9}[A-Za-z]$')])),
                ('bhf_id', models.CharField(default='00', max_length=50)),
                ('device_serial', models.CharField(default='BHF0018902', max_length=100)),
                ('is_production', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
