# Generated by Django 5.0.14 on 2026-09-29 07:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_paymentreference_refund_refunditem_saletaxline_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('merchant_request_id', models.CharField(max_length=100)),
                ('checkout_request_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('amount_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_for_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stk_requests', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('transaction_type', models.CharField(default='CustomerPayBillOnline', max_length=50)),
                ('trans_id', models.CharField(max_length=50)),
                ('trans_time', models.CharField(max_length=30)),
                ('trans_amount_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('business_short_code', models.CharField(max_length=30)),
                ('bill_ref_number', models.CharField(blank=True, max_length=100)),
                ('msisdn', models.CharField(max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='sales.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'trans_id'], name='mpesa_mpesa_tenant__75e3d5_idx'), models.Index(fields=['tenant', 'bill_ref_number'], name='mpesa_mpesa_tenant__dc36c2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'trans_id'), name='uniq_mpesa_trans_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='stkrequest',
            constraint=models.UniqueConstraint(fields=('tenant', 'merchant_request_id'), name='uniq_stk_merchant_req_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='stkrequest',
            constraint=models.UniqueConstraint(fields=('tenant', 'checkout_request_id'), name='uniq_stk_checkout_req_per_tenant'),
        ),
    ]
